name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
		npm install gulp gulp-zip del delete-empty gulp-replace-task gulp-sort gulp-wp-pot
        gulp build:potFile
        gulp build:plugin
        gulp zip:pluginForGithub
    - name: WordPress Plugin Deploy
      uses: geargag/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
